name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependences
      run: | 
        pod repo update
        pod install
    - name: Generate xcodeproj
      run: swift package generate-xcodeproj
    - name: Run tests
      run: xcodebuild build test -destination ‘name=iPhone 11’ -scheme ‘MQF’
