name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Bundle Install
      run: bundle install
    - name: Dependencies
      run: bundle exec pod install
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
